apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dev-deployment
spec:
  replicas: 6 # 원하는 Pod 개수를 정의합니다.
  selector:
    matchLabels:
      app: my-dev-app # Deployment가 관리할 Pod을 식별하기 위한 레이블
  template:
    metadata:
      labels:
        app: my-dev-app # Pod에 부여할 레이블
    spec:
      containers:
      - name: dev-container
        image: ghcr.io/ej31/jeff-ex:1.3-amd64
        ports:
        - containerPort: 3000
      nodeSelector:
        env: "dev"
