apiVersion: apps/v1
kind: Deployment
metadata:
  name: emptydir-multi-container
spec:
  replicas: 4
  selector:
    matchLabels:
      app: emptydir-multi-container
  template:
    metadata:
      labels:
        app: emptydir-multi-container
    spec:
      containers:
        - name: container-a
          image: ghcr.io/ej31/jeff-ex:1.3-amd64
          imagePullPolicy: IfNotPresent # 이미지가 로컬에 없을 때만 pull 
          volumeMounts:
            - name: shared-volume
              mountPath: /usr/src/app/shared
          ports:
            - containerPort: 3000      # express라서 기본 3000 포트를 사용함

        - name: container-b
          image: ghcr.io/ej31/jeff-ex-port2000:1.1-amd64
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: shared-volume
              mountPath: /usr/src/app/shared
          ports:
            - containerPort: 2000

      volumes:
        - name: shared-volume
          emptyDir: {}
