apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeaffinity-preferred-multi
spec:
  replicas: 20
  selector:
    matchLabels:
      app: nodeaffinity-preferred-multi
  template:
    metadata:
      labels:
        app: nodeaffinity-preferred-multi
    spec:
      containers:
      - name: nodeaffinity-preferred-multi-container
        image: ghcr.io/ej31/jeff-ex:1.3-amd64
        ports:
        - containerPort: 3000
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          # 첫 번째 선호 조건
          - weight: 2
            preference:
              matchExpressions:
              - key: region
                operator: In
                values:
                - us-east
          # 두 번째 선호 조건
          - weight: 1
            preference:
              matchExpressions:
              - key: environment
                operator: In
                values:
                - production
