apiVersion: v1
kind: Pod
metadata:
  name: nodename-demo
spec:
  # 꼭 nodeName을 설정해야 합니다.
  nodeName: worker3
  containers:
  - name: nodename-demo-container
    image: ghcr.io/ej31/jeff-ex:1.3-amd64
    ports:
      - containerPort: 3000
