apiVersion: v1
kind: Pod
metadata:
  name: jeff-pod
  labels:
    app: jeff-ex
    version: v1
spec:
  containers:
    - name: jeff-container
      image: ghcr.io/ej31/jeff-ex:1.3-amd64
      ports:
        - containerPort: 3000
